name: Security
on: [push, pull_request]

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Check for vulnerabilities
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Go version
        id: go-version
        run: |
          GO_VERSION=$(go mod edit -json | jq -r .Go)
          echo "go-version=$GO_VERSION" >> "$GITHUB_OUTPUT"

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ steps.go-version.outputs.go-version }}
          go-package: ./...